const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
const FETCH_ROBOTS_ASYNC = "FETCH_ROBOTS_ASYNC";
const FETCH_ROBOTS_SUCCESS = "FETCH_ROBOTS_SUCCESS";
const FETCH_ROBOTS_FAILURE = "FETCH_ROBOTS_FAILURE";

export {
    CHANGE_SEARCH_FIELD,
    FETCH_ROBOTS_ASYNC,
    FETCH_ROBOTS_SUCCESS,
    FETCH_ROBOTS_FAILURE
}